### ISSUE TITLE
I ported this to a proper BASH script.

### ISSUE THREAD

**Issue by techmouse** [tetration/Simcity_3000_Linux_Installer#3]
I hope you don't mind me doing this.
https://pastebin.com/46Yh1GWu

**Comment by tetration** [comment]
Not at all, by the way, thank you for making a bash version and leaving the credits of the original version for me. 

@techmouse Would you like to make a pull request to add the bash version to this repository?

**Comment by techmouse** [comment]
> Not at all, by the way, thank you for making a bash version and leaving the credits of the original version for me.
> 
> @techmouse Would you like to make a pull request to add the bash version to this repository?

No problem. I'm happy to help.

I'll let you do the pull request though. I hate doing pull requests.

**Comment by tetration** [comment]
@techmouse since you didn't want to do the honors of making the pull request. I've added your bash script to the repository myself. Thanks again for taking your time to port my python script to bash scripting language. I'm sure it will help many fans to continue playing this game on modern Linux distributions that don't use Python 2.7 anymore.
